### ISSUE TITLE
--DELETED--

### ISSUE THREAD

**Issue by 1nikolas** [onigetoc/m3u8-PHP-Parser#1]
--DELETED--

**Comment by onigetoc** [comment]
Hi, i saw the question in my email and you should have a HLS m3u8 video player like this one to play these videos: 
http://www.scriptsmashup.com/product/video-pro-skin-builder-wordpress-html5-youtube-plugin

**Comment by 1nikolas** [comment]
okay thanks for the answer. I have a question. Why when I use [your parser](http://codesniff.com/scripts/GC-m3u-parser/GC-m3u-parser.php) everything is okay but when I use [this](https://github.com/onigetoc/m3u8-PHP-Parser/blob/master/m3u-parser-simple.php) everything is undefined and when I use [this](https://github.com/onigetoc/m3u8-PHP-Parser/blob/master/m3u-parser.php) I get one channel only named iptv? (php files are on my server)
EDIT: I also use [this js](https://github.com/onigetoc/m3u8-PHP-Parser/blob/master/getm3upls.js) to get the list on the html.

**Comment by onigetoc** [comment]
The js file is only a example and it may not be up to date, you should modify it to your need. Load the php file or see your console.log to parse it with javascripts or jQuery.

**Comment by 1nikolas** [comment]
but [this thing](http://codesniff.com/scripts/GC-m3u-parser/GC-m3u-parser.php) works. Could you please send me that file?

**Comment by onigetoc** [comment]
I added this jQuery codes for simple parser.
https://github.com/onigetoc/m3u8-PHP-Parser/blob/master/getm3upls-simple.js

**Comment by 1nikolas** [comment]
Thank you so much. I'll try it tomorrow (here its 11:00pm)
